version: '3.8'

services:
  # 1. Database
  mysql:
    image: mysql:8.0
    environment:
      MYSQL_ROOT_PASSWORD: rootpassword
      MYSQL_DATABASE: scheduler_db
    ports:
      - "3306:3306"
    volumes:
      - mysql_data:/var/lib/mysql
    healthcheck:
      test: ["CMD", "mysqladmin" ,"ping", "-h", "localhost"]
      timeout: 20s
      retries: 10

  # 2. Redis Queue
  redis:
    image: redis:alpine
    ports:
      - "6379:6379"

  # 3. Setup Script (Runs once to create tables)
  setup:
    build: .
    command: npm run setup
    environment:
      DB_HOST: mysql
      DB_USER: root
      DB_PASS: rootpassword
      DB_NAME: scheduler_db
      REDIS_URL: redis://redis:6379
    depends_on:
      mysql:
        condition: service_healthy

  # 4. API Server
  api:
    build: .
    command: node src/server.js
    ports:
      - "3000:3000"
    environment:
      DB_HOST: mysql
      DB_USER: root
      DB_PASS: rootpassword
      DB_NAME: scheduler_db
      REDIS_URL: redis://redis:6379
      PORT: 3000
    depends_on:
      mysql:
        condition: service_healthy
      redis:
        condition: service_started

  # 5. Dispatcher (HA: Running 2 instances)
  dispatcher:
    build: .
    command: node src/dispatcher.js
    deploy:
      replicas: 2  # <--- BONUS 2: High Availability
    environment:
      DB_HOST: mysql
      DB_USER: root
      DB_PASS: rootpassword
      DB_NAME: scheduler_db
      REDIS_URL: redis://redis:6379
    depends_on:
      setup:
        condition: service_completed_successfully

  # 6. Worker (Scalability: Running 3 instances)
  worker:
    build: .
    command: node src/worker.js
    deploy:
      replicas: 3  # <--- BONUS 2: Scalability
    environment:
      DB_HOST: mysql
      DB_USER: root
      DB_PASS: rootpassword
      DB_NAME: scheduler_db
      REDIS_URL: redis://redis:6379
    depends_on:
      setup:
        condition: service_completed_successfully

volumes:
  mysql_data: